// Party directory for /investors.html. Contacts as published on each firm's own site or an official register, checked 18 Sep 2026. Edit and commit to update.
window.MAP_DIRECTORY = [
{
"role": "indian_counsel",
"name": "Tusshar Pawar",
"firm": "Advocate, Mumbai",
"email": "",
"phone": "",
"website": "",
"city": "Mumbai",
"licence_ref": "Bar Council of Maharashtra and Goa enrolment: to record",
"note": "India side counsel for FEMA, LRS, TCS and Indian tax residency; also lead for Dubai golden visa clients. Add email and phone."
},
{
"role": "indian_counsel",
"name": "To be appointed",
"firm": "Indian counsel",
"email": "",
"phone": "",
"website": "",
"city": "",
"licence_ref": "",
"note": "Placeholder."
},
{
"role": "law_firm",
"name": "Lane Neave",
"firm": "Lane Neave",
"email": "",
"phone": "+64 9 300 6263",
"website": "https://www.laneneave.co.nz",
"city": "Auckland, Wellington, Christchurch, Queenstown",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "Leading AIP immigration practice; enquiries via web form."
},
{
"role": "law_firm",
"name": "Duncan Cotterill",
"firm": "Duncan Cotterill",
"email": "auckland@duncancotterill.com",
"phone": "+64 9 309 1948",
"website": "https://duncancotterill.com",
"city": "Auckland and other centres",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "Immigration practice covering AIP and Business Investor Visa."
},
{
"role": "law_firm",
"name": "Queen City Law",
"firm": "Queen City Law",
"email": "law@queencitylaw.co.nz",
"phone": "+64 9 970 8810",
"website": "https://www.queencitylaw.co.nz",
"city": "Auckland",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "Level 8, 19 Victoria Street West; multilingual investor team."
},
{
"role": "adviser",
"name": "Immigration Chambers (IC Legal)",
"firm": "Immigration Chambers",
"email": "advice@iclegal.co.nz",
"phone": "+64 9 218 9991",
"website": "https://iclegal.co.nz",
"city": "Auckland",
"licence_ref": "Check IAA register",
"note": "Licensed advisers plus lawyers via Fisher Foley. Licence numbers not published on site."
},
{
"role": "adviser",
"name": "New Zealand Immigration Partners",
"firm": "New Zealand Immigration Partners (formerly Malcolm Pacific)",
"email": "info@nzimmigrationpartners.com",
"phone": "+64 9 309 4187",
"website": "https://www.nzimmigrationpartners.com",
"city": "Auckland, Tauranga, Wellington, Queenstown",
"licence_ref": "Check IAA register",
"note": "Freephone 0800 800 612. Dedicated AIP page."
},
{
"role": "adviser",
"name": "P&H Partners",
"firm": "P&H Partners",
"email": "info@phpartners.co.nz",
"phone": "+91 92118 64333",
"website": "https://www.phpartners.co.nz",
"city": "Auckland and Gurugram (India)",
"licence_ref": "IAA 200800600 per site footer; confirm on register",
"note": "Licensed NZ advisers with India office; dedicated AIP page for Indian investors."
},
{
"role": "adviser",
"name": "Simon Park, Immigration Trust NZ",
"firm": "Immigration Trust NZ",
"email": "info@immigrationtrust.co.nz",
"phone": "+64 9 918 2484",
"website": "https://www.immigrationtrust.co.nz",
"city": "Auckland",
"licence_ref": "IAA 201400550 per profile page; confirm on register",
"note": "26 Hobson Street, Auckland Central."
},
{
"role": "law_firm",
"name": "Parry Field Lawyers",
"firm": "Parry Field Lawyers",
"email": "immigration@parryfield.com",
"phone": "+64 3 348 8480",
"website": "https://www.parryfield.com",
"city": "Christchurch and Auckland",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "Runs an AIP information hub; Auckland +64 9 930 4340."
},
{
"role": "law_firm",
"name": "Fragomen (Auckland)",
"firm": "Fragomen",
"email": "",
"phone": "",
"website": "https://www.fragomen.com/offices/auckland.html",
"city": "Auckland",
"licence_ref": "Law firm / check IAA register",
"note": "Global immigration firm; no NZ phone or email published."
},
{
"role": "adviser",
"name": "Pathways to New Zealand",
"firm": "Pathways to New Zealand",
"email": "enquiry@pathwaysnz.com",
"phone": "+64 7 834 9222",
"website": "https://www.pathwaysnz.com",
"city": "Hamilton and Wellington",
"licence_ref": "Check IAA register",
"note": "Ten licensed advisers; 0508 728 492 within NZ."
},
{
"role": "law_firm",
"name": "Bell Gully",
"firm": "Bell Gully",
"email": "info@bellgully.com",
"phone": "+64 9 916 8800",
"website": "https://www.bellgully.com",
"city": "Auckland and Wellington",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "Large commercial firm; private wealth support for investor migrants."
},
{
"role": "law_firm",
"name": "Simpson Grierson",
"firm": "Simpson Grierson",
"email": "",
"phone": "+64 9 358 2222",
"website": "https://www.simpsongrierson.com",
"city": "Auckland, Wellington, Christchurch",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "Contact via web form."
},
{
"role": "law_firm",
"name": "Anthony Harper",
"firm": "Anthony Harper",
"email": "info@ah.co.nz",
"phone": "+64 9 920 6400",
"website": "https://www.ah.co.nz",
"city": "Auckland and Christchurch",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": ""
},
{
"role": "law_firm",
"name": "Chapman Tripp",
"firm": "Chapman Tripp",
"email": "",
"phone": "+64 9 357 9000",
"website": "https://chapmantripp.com",
"city": "Auckland, Wellington, Christchurch",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "General enquiries via web form."
},
{
"role": "law_firm",
"name": "Turner Hopkins",
"firm": "Turner Hopkins",
"email": "law@turnerhopkins.co.nz",
"phone": "+64 9 486 2169",
"website": "https://www.turnerhopkins.co.nz",
"city": "Auckland (Takapuna)",
"licence_ref": "Law firm: lawyers are exempt from IAA licensing",
"note": "North Shore firm with an investor migrant practice."
},
{
"role": "adviser",
"name": "Immigration Advisers New Zealand Ltd (IANZ)",
"firm": "Immigration Advisers New Zealand Ltd",
"email": "contact@nzimmigration.info",
"phone": "+64 9 379 0219",
"website": "https://nzimmigration.info",
"city": "Auckland, Jammu, Kathmandu",
"licence_ref": "Check IAA register",
"note": "Dedicated AIP page; WhatsApp +64 29 774 2233."
},
{
"role": "fund_manager",
"name": "2026 Koru Education and Childcare Fund LP",
"firm": "Koru",
"email": "",
"phone": "",
"website": "https://koruchildcarefund.co.nz",
"city": "",
"licence_ref": "Invest NZ list 15 Jul 2026",
"note": "Private equity and private credit; NZ education infrastructure."
},
{
"role": "fund_manager",
"name": "Punakaiki Fund (PFL)",
"firm": "2040 Ventures",
"email": "info@punakaikifund.co.nz",
"phone": "",
"website": "https://punakaikifund.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 18 May 2023",
"note": "Venture capital; $145m evergreen, quarterly liquidity via Catalist."
},
{
"role": "fund_manager",
"name": "Climate Venture Capital Fund 2",
"firm": "2040 Ventures",
"email": "contact@climatevcfund.com",
"phone": "+64 21 410 861",
"website": "https://climatevcfund.com",
"city": "Auckland",
"licence_ref": "Invest NZ list 14 Dec 2023",
"note": "Venture capital; targets 25% IRR."
},
{
"role": "fund_manager",
"name": "AAM Infrastructure Loan Fund",
"firm": "Aotea Asset Management",
"email": "investors@aotea-am.co.nz",
"phone": "+64 21 909 795",
"website": "https://aotea-am.co.nz",
"city": "",
"licence_ref": "Invest NZ list 4 Mar 2026",
"note": "Infrastructure; senior secured loans."
},
{
"role": "fund_manager",
"name": "AANZ (Aviation Aerospace NZ)",
"firm": "Bancorp Wealth Management Group",
"email": "mevans@bancorp.co.nz",
"phone": "+64 9 309 8270",
"website": "https://aanzfund.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 27 Aug 2025",
"note": "Private capital; helicopter leasing; liquidity after 3 years."
},
{
"role": "fund_manager",
"name": "ACIF NZ Investment Fund",
"firm": "ACIF",
"email": "",
"phone": "",
"website": "https://acif.co.nz",
"city": "",
"licence_ref": "Invest NZ list 4 Sep 2025",
"note": "Private credit; SME debt and equity."
},
{
"role": "fund_manager",
"name": "Active Long Term Growth Fund",
"firm": "ForthCo Limited",
"email": "Adam.paterson@forthco.nz",
"phone": "+64 21 156 9070",
"website": "https://forthco.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 27 Aug 2025",
"note": "Private equity; evergreen LP."
},
{
"role": "fund_manager",
"name": "Amber & Partners Infrastructure NZ Fund",
"firm": "Amber Infrastructure",
"email": "",
"phone": "",
"website": "https://www.amberinfrastructure.com",
"city": "London (NZ fund)",
"licence_ref": "Invest NZ list 15 Dec 2025",
"note": "Infrastructure; evergreen with redemption windows."
},
{
"role": "fund_manager",
"name": "ARC Capital",
"firm": "ARC Capital Management",
"email": "investment@nzarc.co.nz",
"phone": "0800 692 724",
"website": "https://arccapital.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 27 Aug 2025",
"note": "Private equity; aged care and healthcare."
},
{
"role": "fund_manager",
"name": "Altered Capital Venture Fund II",
"firm": "Altered Capital",
"email": "contact@alteredcapital.com",
"phone": "",
"website": "https://alteredcapital.com",
"city": "Auckland",
"licence_ref": "Invest NZ list 23 Jan 2025",
"note": "Venture capital and private equity."
},
{
"role": "fund_manager",
"name": "BeGroup Investments II LP",
"firm": "BeGroup",
"email": "",
"phone": "+64 9 972 0920",
"website": "https://thebegroup.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 10 Nov 2025",
"note": "Infrastructure; retirement villages."
},
{
"role": "fund_manager",
"name": "Blairlogie Pine Investment",
"firm": "Forest Enterprises",
"email": "info@forestenterprises.co.nz",
"phone": "+64 6 370 6360",
"website": "https://forestenterprises.co.nz",
"city": "Masterton",
"licence_ref": "Invest NZ list 17 Dec 2025",
"note": "Private equity; forestry; 9.8% projected IRR."
},
{
"role": "fund_manager",
"name": "Blossum AIP Fund",
"firm": "Blossum",
"email": "info@blossum.nz",
"phone": "0508 462 663",
"website": "https://blossum.nz",
"city": "",
"licence_ref": "Invest NZ list 10 Mar 2026",
"note": "Private credit; SME secured lending."
},
{
"role": "fund_manager",
"name": "Blue Ocean Capital Group Plus LP",
"firm": "PCG Global / Dreamhome Group",
"email": "",
"phone": "",
"website": "",
"city": "",
"licence_ref": "Invest NZ list 19 Nov 2025",
"note": "Infrastructure; solar; gross IRR 12.5 to 14.5% target."
},
{
"role": "fund_manager",
"name": "Boston ME Economic Growth Fund",
"firm": "Eccuity",
"email": "",
"phone": "",
"website": "https://eccuity.com",
"city": "Auckland",
"licence_ref": "Invest NZ list 22 Dec 2025",
"note": "Private capital; wholesale only."
},
{
"role": "fund_manager",
"name": "Bridgewest Venture Fund 1 LP",
"firm": "Bridgewest",
"email": "info@bridgewest.ventures",
"phone": "",
"website": "https://bridgewest.ventures",
"city": "Auckland and Wellington",
"licence_ref": "Invest NZ list 5 Aug 2025",
"note": "Venture capital; deep tech; zero carry."
},
{
"role": "fund_manager",
"name": "Capital Connect No.1 LP",
"firm": "Capital Connect",
"email": "",
"phone": "",
"website": "https://capitalconnect.co.nz",
"city": "",
"licence_ref": "Invest NZ list 17 Dec 2025",
"note": "Private credit; target net 5 to 7% p.a."
},
{
"role": "fund_manager",
"name": "Castlerock Partners",
"firm": "Bancorp",
"email": "matthew@castlerockpartners.co.nz",
"phone": "+64 9 309 8270",
"website": "https://castlerockpartners.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 2 Dec 2024",
"note": "Private equity; open ended; targets 8% p.a."
},
{
"role": "fund_manager",
"name": "Craigmore Farming NZ LP",
"firm": "Craigmore Sustainables",
"email": "investorrelations@craigmore.com",
"phone": "+64 3 344 0090",
"website": "https://craigmore.com",
"city": "Christchurch",
"licence_ref": "Invest NZ list 28 Jul 2026",
"note": "Private equity; farming."
},
{
"role": "fund_manager",
"name": "Cultivate Ventures LP",
"firm": "Cultivate Ventures",
"email": "info@cultivateventures.co.nz",
"phone": "+64 9 913 4608",
"website": "https://cultivateventures.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 2 Nov 2023",
"note": "Venture capital; agri tech; 15% IRR target."
},
{
"role": "fund_manager",
"name": "Ecliptic Venture Capital LP",
"firm": "Ecliptic",
"email": "david@eclipticvc.com",
"phone": "",
"website": "https://eclipticvc.com",
"city": "",
"licence_ref": "Invest NZ list 4 Apr 2024",
"note": "Venture capital; seed and Series A."
},
{
"role": "fund_manager",
"name": "Emerald Timberland Impact Fund",
"firm": "Roger Dickie New Zealand",
"email": "invest@rogerdickie.co.nz",
"phone": "+64 6 346 5329",
"website": "https://rogerdickie.co.nz",
"city": "Whanganui",
"licence_ref": "Invest NZ list 10 Nov 2025",
"note": "Private equity; forestry."
},
{
"role": "fund_manager",
"name": "Fidelity Capital Sustainable Energy Fund",
"firm": "Fidelity Capital Partners",
"email": "",
"phone": "",
"website": "https://www.fc-energy.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 13 Sep 2023",
"note": "Private credit; each investment matures in 3 years."
},
{
"role": "fund_manager",
"name": "GD1 Fund 4",
"firm": "GD1",
"email": "info@gd1.vc",
"phone": "",
"website": "https://gd1.vc",
"city": "Auckland",
"licence_ref": "Invest NZ list 3 Jul 2025",
"note": "Venture capital; target $150m."
},
{
"role": "fund_manager",
"name": "GD1 Select Fund",
"firm": "GD1",
"email": "info@gd1.vc",
"phone": "",
"website": "https://gd1.vc",
"city": "Auckland",
"licence_ref": "Invest NZ list 25 May 2026",
"note": "Venture capital; 7 to 10 portfolio companies."
},
{
"role": "fund_manager",
"name": "Goldenstone Partners LP",
"firm": "Goldenstone Partners Capital",
"email": "info@goldenstonecapital.co.nz",
"phone": "",
"website": "https://goldenstonecapital.co.nz",
"city": "",
"licence_ref": "Invest NZ list 15 Jun 2026",
"note": "Private credit; hurdle 6% p.a."
},
{
"role": "fund_manager",
"name": "Goldsmith Tourism NZ LP",
"firm": "Goldsmith",
"email": "",
"phone": "",
"website": "",
"city": "",
"licence_ref": "Invest NZ list 23 Dec 2025",
"note": "Private credit; tourism; target net 3 to 6%."
},
{
"role": "fund_manager",
"name": "GreenMount Capital Private Equity Fund II",
"firm": "GreenMount Capital",
"email": "",
"phone": "",
"website": "https://greenmount.com",
"city": "Auckland",
"licence_ref": "Invest NZ list 15 Jul 2026",
"note": "Private equity; close date 31 Dec 2026."
},
{
"role": "fund_manager",
"name": "Greener Pastures Diversified Fund",
"firm": "Origin Capital Partners",
"email": "mischa@greenerpastures.nz",
"phone": "+64 21 578 054",
"website": "https://greenerpastures.nz",
"city": "",
"licence_ref": "Invest NZ list 13 Jan 2025",
"note": "Fund of funds; in house licensed immigration adviser."
},
{
"role": "fund_manager",
"name": "Greener Pastures Kiwifruit Fund",
"firm": "Greener Pastures",
"email": "mischa@greenerpastures.nz",
"phone": "+64 21 578 054",
"website": "https://greenerpastures.nz",
"city": "",
"licence_ref": "Invest NZ list 3 Jul 2025",
"note": "Private equity; kiwifruit; 50% liquidity year 4."
},
{
"role": "fund_manager",
"name": "Henton Fund 2",
"firm": "Henton Capital",
"email": "investors@hentoncapital.com",
"phone": "",
"website": "https://hentoncapital.com",
"city": "Auckland",
"licence_ref": "Invest NZ list 1 May 2025",
"note": "Private credit; not currently seeking outside investors."
},
{
"role": "fund_manager",
"name": "Hunter Diversified Private Credit Fund",
"firm": "Hunter Investment Management",
"email": "contact@hunterinvestments.co.nz",
"phone": "0800 460 830",
"website": "https://hunterinvestments.co.nz",
"city": "Wellington",
"licence_ref": "Invest NZ list 12 Jun 2025",
"note": "Private credit; monthly subscriptions and redemptions."
},
{
"role": "fund_manager",
"name": "Icehouse Ventures Growth Fund III",
"firm": "Icehouse Ventures",
"email": "hello@icehouseventures.co.nz",
"phone": "",
"website": "https://icehouseventures.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 25 May 2026",
"note": "Venture capital; Series A to D+."
},
{
"role": "fund_manager",
"name": "IV Sustainable Technology Fund",
"firm": "Icehouse Ventures",
"email": "hello@icehouseventures.co.nz",
"phone": "",
"website": "https://icehouseventures.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 11 Apr 2024",
"note": "Venture capital; seed impact."
},
{
"role": "fund_manager",
"name": "Kākāpō Responsible Investment Fund",
"firm": "Bancorp",
"email": "admin@bancorp.co.nz",
"phone": "+64 9 309 8270",
"website": "https://kakapofund.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 31 May 2023",
"note": "Private equity; quarterly distributions; exit liquidity after 3 years."
},
{
"role": "fund_manager",
"name": "Mana Tupu Capital NZ Venture Fund I",
"firm": "Mana Tupu Capital",
"email": "invest@manatupu.co.nz",
"phone": "+64 9 802 2829",
"website": "https://manatupu.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 24 Aug 2026",
"note": "Venture capital; Series A and B."
},
{
"role": "fund_manager",
"name": "MA NZ Growth Fund",
"firm": "MA Financial / Elevation Capital",
"email": "MAclientservices@mafinancial.com",
"phone": "+64 9 873 5597",
"website": "https://mafinancial.com/invest/investment-migration-solutions/investor-nzaip-visa",
"city": "Auckland",
"licence_ref": "Invest NZ list 4 Sep 2025",
"note": "Multi strategy; private credit and operating real estate."
},
{
"role": "fund_manager",
"name": "Matū Karihi Fund",
"firm": "Matū",
"email": "info@matu.co.nz",
"phone": "",
"website": "https://matu.co.nz",
"city": "",
"licence_ref": "Invest NZ list 10 Mar 2023",
"note": "Venture capital; deep science."
},
{
"role": "fund_manager",
"name": "Maūi Toa Fund 1",
"firm": "Maui Toa",
"email": "info@mauitoa.vc",
"phone": "+64 21 428 075",
"website": "https://mauitoa.vc",
"city": "Auckland and Christchurch",
"licence_ref": "Invest NZ list 20 Mar 2025",
"note": "Venture capital; Māori owned and led."
},
{
"role": "fund_manager",
"name": "Motion Capital Fund II LP",
"firm": "Motion Capital",
"email": "enquiries@motioncapital.co.nz",
"phone": "",
"website": "https://motioncapital.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 2 Jun 2026",
"note": "Venture capital; climate tech (Fund I is closed)."
},
{
"role": "fund_manager",
"name": "Movac Growth 7",
"firm": "Movac",
"email": "hello@movac.co.nz",
"phone": "",
"website": "https://movac.co.nz",
"city": "",
"licence_ref": "Invest NZ list 1 Dec 2025",
"note": "Venture capital; close date 1 Oct 2026."
},
{
"role": "fund_manager",
"name": "MTM Capital One",
"firm": "MTM",
"email": "",
"phone": "",
"website": "",
"city": "",
"licence_ref": "Invest NZ list 13 May 2025",
"note": "Private equity; invite only."
},
{
"role": "fund_manager",
"name": "MyFarm Kiwifruit Fund LP",
"firm": "MyFarm Investments",
"email": "comms@myfarm.co.nz",
"phone": "0800 693 276",
"website": "https://myfarm.co.nz",
"city": "",
"licence_ref": "Invest NZ list 16 Sep 2025",
"note": "Private equity; kiwifruit; target 10% p.a."
},
{
"role": "fund_manager",
"name": "MyFarm Solar Fund LP",
"firm": "MyFarm Investments",
"email": "comms@myfarm.co.nz",
"phone": "0800 693 276",
"website": "https://myfarm.co.nz",
"city": "",
"licence_ref": "Invest NZ list 7 Jul 2025",
"note": "Private equity; solar; 10 to 12% p.a. projected."
},
{
"role": "fund_manager",
"name": "NetCredit Unit Trust",
"firm": "NetFunds",
"email": "info@netfunds.co.nz",
"phone": "",
"website": "https://netfunds.co.nz",
"city": "Christchurch",
"licence_ref": "Invest NZ list 26 Sep 2025",
"note": "Private credit; PIE; OCR + 7% target."
},
{
"role": "fund_manager",
"name": "NetEquity Opportunities Fund LP",
"firm": "NetFunds",
"email": "info@netfunds.co.nz",
"phone": "",
"website": "https://netfunds.co.nz",
"city": "Christchurch",
"licence_ref": "Invest NZ list 10 Nov 2025",
"note": "Private equity; fund of funds plus direct SME."
},
{
"role": "fund_manager",
"name": "Newland Credit Fund",
"firm": "Newland",
"email": "invest@ncf.co.nz",
"phone": "",
"website": "https://ncf.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 17 Sep 2025",
"note": "Private credit; direct lending."
},
{
"role": "fund_manager",
"name": "Nexus Fund I LP",
"firm": "Nexus Capital Management",
"email": "op@ncmfund.com.nz",
"phone": "",
"website": "https://ncmfund.co.nz",
"city": "",
"licence_ref": "Invest NZ list 10 Nov 2025",
"note": "Fund of funds; private equity."
},
{
"role": "fund_manager",
"name": "Northland Capital Partners Fund",
"firm": "Northland Capital Partners",
"email": "dean@northlandcapitalpartners.com",
"phone": "",
"website": "https://northlandcapitalpartners.com",
"city": "Whangarei",
"licence_ref": "Invest NZ list 29 Jul 2026",
"note": "Private equity; horticulture and water."
},
{
"role": "fund_manager",
"name": "NZVC Fund 2",
"firm": "NZVC",
"email": "",
"phone": "",
"website": "https://nzvc.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 27 Mar 2025",
"note": "Venture capital; close date 31 Dec 2026."
},
{
"role": "fund_manager",
"name": "Outset Momentum Fund I",
"firm": "Outset Ventures",
"email": "hello@outset.ventures",
"phone": "",
"website": "https://outset.ventures",
"city": "Auckland",
"licence_ref": "Invest NZ list 23 Dec 2025",
"note": "Venture capital; deep tech Series A and B."
},
{
"role": "fund_manager",
"name": "Pacific Channel Fund V",
"firm": "Pacific Channel",
"email": "enquiries@pacificchannel.com",
"phone": "+64 9 376 0382",
"website": "https://pacificchannel.com",
"city": "Auckland",
"licence_ref": "Invest NZ list 22 Aug 2025",
"note": "Private credit; renewable energy debt; 8% interest plus success fee."
},
{
"role": "fund_manager",
"name": "Pacific Channel Fund III",
"firm": "Pacific Channel",
"email": "enquiries@pacificchannel.com",
"phone": "+64 9 376 0382",
"website": "https://pacificchannel.com",
"city": "Auckland",
"licence_ref": "Invest NZ list 24 Mar 2023",
"note": "Venture capital; deep tech."
},
{
"role": "fund_manager",
"name": "PCG Diversified New Zealand Private Debt Fund",
"firm": "Private Capital Group",
"email": "",
"phone": "",
"website": "https://privatecapitalgroup.co.nz",
"city": "Auckland and Queenstown",
"licence_ref": "Invest NZ list 1 May 2023",
"note": "Private credit; open ended PIE; weekly liquidity."
},
{
"role": "fund_manager",
"name": "PCG New Zealand Economic Resilience Fund",
"firm": "Private Capital Group",
"email": "",
"phone": "",
"website": "https://privatecapitalgroup.co.nz",
"city": "Auckland and Queenstown",
"licence_ref": "Invest NZ list 3 Feb 2026",
"note": "Private credit; infrastructure and real asset loans."
},
{
"role": "fund_manager",
"name": "Peninsula Credit Fund II LP",
"firm": "Peninsula Credit",
"email": "contact@peninsulacredit.co.nz",
"phone": "",
"website": "https://peninsulacredit.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 14 Jul 2025",
"note": "Private credit; open ended LP; quarterly cash."
},
{
"role": "fund_manager",
"name": "Perennial Roots LP",
"firm": "Perennial",
"email": "",
"phone": "",
"website": "https://perennialfarming.co.nz",
"city": "",
"licence_ref": "Invest NZ list 20 Oct 2025",
"note": "Private equity; regenerative organic farming."
},
{
"role": "fund_manager",
"name": "Pioneer Capital Diversified Fund",
"firm": "Pioneer Capital",
"email": "",
"phone": "+64 9 304 0870",
"website": "https://pioneercapital.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 24 Dec 2025",
"note": "Multi strategy; $1.3b wholesale capital raised to date."
},
{
"role": "fund_manager",
"name": "Pioneer Capital Private Equity V",
"firm": "Pioneer Capital",
"email": "",
"phone": "+64 9 304 0870",
"website": "https://pioneercapital.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 3 Jul 2025",
"note": "Private equity."
},
{
"role": "fund_manager",
"name": "Quidnet Ventures Fund II",
"firm": "Quidnet Ventures",
"email": "",
"phone": "",
"website": "https://quidnetventures.com",
"city": "",
"licence_ref": "Invest NZ list 16 Apr 2025",
"note": "Venture capital; deep tech."
},
{
"role": "fund_manager",
"name": "RAM NZ Credit Fund",
"firm": "RAM Group",
"email": "info@ramgroup.com",
"phone": "",
"website": "https://ramgroup.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 17 Dec 2025",
"note": "Private credit; SME credit; investment immigration for 13 years."
},
{
"role": "fund_manager",
"name": "Rānui Sunshine Fund",
"firm": "SC Capital Partners (Ranui Generation)",
"email": "investor@ranuigen.co.nz",
"phone": "",
"website": "https://ranuigen.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 20 Jan 2026",
"note": "Infrastructure; solar; target 13 to 15% p.a.; close 31 Dec 2027."
},
{
"role": "fund_manager",
"name": "Runway Private Credit Fund (No.1) LP",
"firm": "Runway Limited",
"email": "hello@runway.co.nz",
"phone": "0800 275 562",
"website": "https://runway.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 17 Aug 2026",
"note": "Private credit; SME secured lending."
},
{
"role": "fund_manager",
"name": "Ryft Fund Zero",
"firm": "Ryft Capital",
"email": "invest@ryft.vc",
"phone": "",
"website": "https://ryftcapital.com",
"city": "",
"licence_ref": "Invest NZ list 13 May 2025",
"note": "Venture capital; venture studio; close 31 Dec 2026."
},
{
"role": "fund_manager",
"name": "SCW Investment Fund LP",
"firm": "SCW",
"email": "",
"phone": "",
"website": "",
"city": "",
"licence_ref": "Invest NZ list 10 Nov 2025",
"note": "Private credit; aged care debt; target net 4 to 8%."
},
{
"role": "fund_manager",
"name": "Seedling Next Gen Agri LP",
"firm": "Seedling Investments",
"email": "",
"phone": "",
"website": "https://seedling-investments.com",
"city": "",
"licence_ref": "Invest NZ list 12 Jun 2025",
"note": "Private equity; dairy; 9% pre tax IRR target."
},
{
"role": "fund_manager",
"name": "Southern Alps Retirement Living Sunrise Fund",
"firm": "Southern Alps",
"email": "contact@southern-alps.co.nz",
"phone": "021 385 518",
"website": "https://southern-alps.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 24 Jul 2025",
"note": "Private equity; retirement villages."
},
{
"role": "fund_manager",
"name": "Tōtara Forestry LP",
"firm": "Craigmore Sustainables",
"email": "investorrelations@craigmore.com",
"phone": "+64 3 344 0090",
"website": "https://craigmore.com",
"city": "Christchurch",
"licence_ref": "Invest NZ list 17 Aug 2026",
"note": "Private equity; forestry."
},
{
"role": "fund_manager",
"name": "WNT Ventures Fund 4",
"firm": "WNT Ventures",
"email": "",
"phone": "",
"website": "https://wntventures.co.nz",
"city": "Tauranga and Auckland",
"licence_ref": "Invest NZ list 8 Aug 2023",
"note": "Venture capital; $35m seed to Series A."
},
{
"role": "fund_manager",
"name": "Yes Capital LP",
"firm": "Yes Capital",
"email": "hello@yescapital.co.nz",
"phone": "+64 21 100 9212",
"website": "https://yescapital.co.nz",
"city": "Auckland",
"licence_ref": "Invest NZ list 14 Apr 2026",
"note": "Private equity; debt based; tourism, agri, manufacturing."
},
{
"role": "accountant",
"name": "William Buck New Zealand",
"firm": "William Buck",
"email": "info@williambuck.co.nz",
"phone": "+64 9 366 5000",
"website": "https://williambuck.com/nz/",
"city": "Auckland",
"licence_ref": "CA ANZ member firm",
"note": "Business advisory and tax for relocating individuals."
},
{
"role": "accountant",
"name": "K3 Chartered Accountants",
"firm": "K3",
"email": "info@k3.co.nz",
"phone": "+64 9 366 1366",
"website": "https://www.k3.co.nz/lp/invest-new-zealand",
"city": "Auckland",
"licence_ref": "CA ANZ member firm",
"note": "Dedicated AIP page: fund due diligence, trust structuring, AML, tax."
},
{
"role": "accountant",
"name": "Acclime New Zealand",
"firm": "Acclime",
"email": "",
"phone": "+64 9 918 3474",
"website": "https://newzealand.acclime.com/solutions/investment-migration/",
"city": "Auckland",
"licence_ref": "Corporate services",
"note": "Investment migration solution and international tax planning."
},
{
"role": "accountant",
"name": "Bellingham Wallace",
"firm": "Bellingham Wallace (Andersen in NZ)",
"email": "support@nz.Andersen.com",
"phone": "+64 9 309 7851",
"website": "https://bellinghamwallace.co.nz",
"city": "Auckland",
"licence_ref": "CA ANZ member firm",
"note": "Publishes transitional tax resident guides for new migrants."
},
{
"role": "accountant",
"name": "Baker Tilly Staples Rodway",
"firm": "Baker Tilly Staples Rodway",
"email": "auckland@bakertillysr.nz",
"phone": "+64 9 309 0463",
"website": "https://bakertillysr.nz",
"city": "Auckland and national",
"licence_ref": "CA ANZ member firm",
"note": "Investor migrant tax commentary; due diligence services."
},
{
"role": "accountant",
"name": "Grant Thornton New Zealand",
"firm": "Grant Thornton",
"email": "",
"phone": "+64 9 308 2570",
"website": "https://www.grantthornton.co.nz",
"city": "Auckland",
"licence_ref": "CA ANZ member firm",
"note": "Web form only."
}
];
