// Indian polo buyers directory, shared by polo.html and proposal.html. Compiled 18 Sep 2026.
window.MAP_POLO_BUYERS = [
  // Military and service teams
  {n:"61st Cavalry",k:"military",c:"Jaipur / Delhi",d:"exempt",x:"The Army's horsed cavalry regiment and the engine of Indian polo; IPA registered office sits with B Squadron at Delhi Cantt. Risaldar Chandra Mohan Singh named Polo Trainer 2026."},
  {n:"President's Bodyguard",k:"military",c:"New Delhi",d:"exempt",x:"Ceremonial cavalry of the President; fields polo teams in the Delhi season and the President's Polo Cup."},
  {n:"Army Polo and Riding Centre (APRC)",k:"military",c:"New Delhi",d:"exempt",x:"Polo Club of the Season, Indian Polo Awards 2026. Home of the Delhi season on the Army grounds."},
  {n:"Indian Navy Polo and Equestrian Club",k:"military",c:"Mumbai",d:"exempt",x:"Navy team; plays the Mumbai season at Mahalakshmi Race Course."},
  {n:"Remount and Veterinary Corps (RVC) Polo Club",k:"military",c:"Meerut",d:"exempt",x:"The corps that breeds and remounts Army horses; a natural first conversation on breed and price."},
  {n:"ASC Polo Club (Army Service Corps)",k:"military",c:"Bengaluru",d:"exempt",x:"ASC Centre and College team; anchors the Bengaluru polo revival."},
  {n:"Artillery Polo Club",k:"military",c:"Nashik (Deolali)",d:"exempt",x:"School of Artillery team."},
  {n:"Fort William Polo Club",k:"military",c:"Kolkata",d:"exempt",x:"Eastern Command; plays alongside Calcutta Polo Club on the Maidan."},
  {n:"National Defence Academy Polo Club",k:"military",c:"Pune (Khadakwasla)",d:"exempt",x:"Cadet polo; the pipeline of future Army players."},
  {n:"Indian Military Academy Polo Club",k:"military",c:"Dehradun",d:"exempt",x:"Runs the only polo academy inside a military academy in India."},
  {n:"Officers Training Academy Polo Club",k:"military",c:"Chennai",d:"exempt",x:"OTA team; Chennai season with Madras Polo and Riders Club."},
  {n:"Central Armed Police Forces (BSF, ITBP, CRPF)",k:"military",c:"Various",d:"exempt",x:"Named in the customs exemption as eligible importers. Which forces field polo teams is to be verified; BSF has mounted units."},
  // Patron and corporate teams
  {n:"Jaipur Polo Team (Sawai Padmanabh Singh)",k:"patron",c:"Jaipur",d:"check",x:"The Maharaja of Jaipur's team; Polo Patron of the Year 2026; toured Clevedon for ponies in January 2025. Jaipur is the first patron conversation."},
  {n:"Jodhpur (Maharaja Gaj Singh II)",k:"patron",c:"Jodhpur",d:"check",x:"Jodhpur Polo and Equestrian Institute and the Jodhpur season are the royal family's; two grass fields, stabling for 40."},
  {n:"Jindal Panther Polo",k:"patron",c:"Delhi / Noida",d:"check",x:"Naveen Jindal's team and the Jindal Polo and Equestrian Foundation; Best Team Low Goal and Best Junior Team 2026; sponsor of the Indian Polo Awards."},
  {n:"Achievers Polo (Rajnigandha Achievers)",k:"patron",c:"Delhi",d:"check",x:"Best Team High Goal 2026; DS Group backed."},
  {n:"Mayfair Polo",k:"patron",c:"Delhi",d:"check",x:"Emerging Polo Patron 2026."},
  {n:"Aravali Polo",k:"patron",c:"Delhi",d:"check",x:"Regular Delhi season team (Baroda Cup finalist)."},
  {n:"Sona Polo",k:"patron",c:"Delhi",d:"check",x:"Sunjay Kapur's team; its future after his death in 2025 is to be confirmed before any approach."},
  // Clubs by centre
  {n:"Rajasthan Polo Club",k:"club",c:"Jaipur",d:"check",x:"Category A centre. The Rambagh ground; runs the Jaipur season and the Maharaja Sawai Man Singh Cup."},
  {n:"Jaipur Riding and Polo Club",k:"club",c:"Jaipur",d:"check",x:""},
  {n:"Chinkara Polo Club",k:"club",c:"Jaipur",d:"check",x:""},
  {n:"Haldighati Polo and Riding Club",k:"club",c:"Jaipur",d:"check",x:""},
  {n:"Cavallo Riding and Polo Club",k:"club",c:"Jaipur",d:"check",x:""},
  {n:"Jodhpur Polo and Equestrian Institute",k:"club",c:"Jodhpur",d:"check",x:"Category A centre."},
  {n:"Imperial Riding and Polo Club",k:"club",c:"Udaipur",d:"check",x:""},
  {n:"Delhi season clubs (Jaipur Polo Ground, APRC)",k:"club",c:"New Delhi",d:"check",x:"Category A centre. Civilian teams play on the Army grounds; Aspen Riding and Polo Academy for learners."},
  {n:"Gurgaon Polo and Equestrian Club",k:"club",c:"Gurugram",d:"check",x:"Founded by Randeep Hooda, Aravalli hills."},
  {n:"Amity Polo Club",k:"club",c:"Noida",d:"check",x:"Category A centre (Noida)."},
  {n:"Amateur Riders' Club",k:"club",c:"Mumbai",d:"check",x:"Category A centre. Mahalakshmi Race Course; the Mumbai season with the Navy."},
  {n:"Calcutta Polo Club",k:"club",c:"Kolkata",d:"check",x:"Category B centre. Founded 1862, oldest polo club still playing anywhere."},
  {n:"Hyderabad Polo and Riding Club",k:"club",c:"Hyderabad",d:"check",x:"Category B centre. Arena Polo Club of the Season 2026."},
  {n:"Hyderabad Choughan Polo Club",k:"club",c:"Hyderabad",d:"check",x:""},
  {n:"Andhra Pradesh Riding Club",k:"club",c:"Hyderabad",d:"check",x:""},
  {n:"Agram Riding and Polo Club",k:"club",c:"Bengaluru",d:"check",x:"Category B centre, with ASC."},
  {n:"Bangalore Amateur Riders Institute",k:"club",c:"Bengaluru",d:"check",x:""},
  {n:"Madras Polo and Riders Club",k:"club",c:"Chennai",d:"check",x:"Category B centre."},
  {n:"Patiala Polo and Riding Club",k:"club",c:"Patiala",d:"check",x:"Category C centre; royal polo history."},
  {n:"Leh Polo Club",k:"club",c:"Leh, Ladakh",d:"check",x:"Category C centre; Ladakh Polo Festival. High altitude, local ponies; a hosting story more than a buyer."},
  {n:"All Manipur Polo Association",k:"club",c:"Imphal",d:"check",x:"Category C centre; Mapal Kangjeibung, the oldest polo ground in the world. Traditional sagol kangjei; local pony breed."},
  {n:"Bhavnagar Polo Club",k:"club",c:"Bhavnagar",d:"check",x:"Hosts national tournaments."},
  {n:"Patrons Polo Club",k:"club",c:"Delhi NCR",d:"check",x:"Best Polo Ground 2026."},
  // Schools and academies
  {n:"Mayo College",k:"academy",c:"Ajmer",d:"full",x:"About 50 horses and 250 students coached; the school of the royal players. A ponies and coaching conversation."},
  {n:"Aspen Riding and Polo Academy",k:"academy",c:"New Delhi",d:"full",x:"Learn to play; Kel's coaching in India could sit here."},
  {n:"Jindal Polo and Equestrian Foundation",k:"academy",c:"Noida",d:"check",x:"Jindal's own grounds and junior programme."},
];
